baseURL = "https://sarah.engineer/"
languageCode = "en-us"
title = "sarah.engineer"
theme = "hyde"
enableEmoji = true
relativeURLs = true

[params]
  themeColor = "theme-base-0d"
  description = "full-stack software engineer â€¢ game designer"

[mediaTypes]
[mediaTypes."text/markdown"]
suffixes = ["md"]

[outputFormats]
  [outputFormats.MD]
    baseName = 'index'
    isPlainText = true
    mediaType = 'text/markdown'

[outputs]
  page = ['HTML', 'MD']
  section = ['HTML', 'MD', 'RSS']
  term = ['HTML', 'MD', 'RSS']
  taxonomy = ['HTML', 'MD', 'RSS']
